kind: PersistentVolume
apiVersion: v1
metadata:
  name: league-db-volume
  labels:
    type: local
    app: leaguevol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/league"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: league-db-claim
  labels:
    app: leaguevol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi