// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTJmRUXjXQPOZJQvh_DuLnT0dKkIn_5Oo',
    appId: '1:766527378071:web:a97597678485de2f044fd2',
    messagingSenderId: '766527378071',
    projectId: 'test-a3553',
    authDomain: 'test-a3553.firebaseapp.com',
    storageBucket: 'test-a3553.appspot.com',
    measurementId: 'G-1D9K921RXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIVUcJq8OrClkxXAJkDZlk7ITHUmT0Eo4',
    appId: '1:766527378071:android:61ce6d4f4d81f50b044fd2',
    messagingSenderId: '766527378071',
    projectId: 'test-a3553',
    storageBucket: 'test-a3553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-jzXFAPKbnW2QE4CavfxRvRbawdmT-k',
    appId: '1:766527378071:ios:a916cb211f3a6bf3044fd2',
    messagingSenderId: '766527378071',
    projectId: 'test-a3553',
    storageBucket: 'test-a3553.appspot.com',
    iosClientId: '766527378071-bvhnctdubjhk2n5rj8l37lpq6q4qobdk.apps.googleusercontent.com',
    iosBundleId: 'com.uniprojects.wannaqapp',
  );
}
