apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  namespace: default
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-app
          image: api_gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          


---
kind: Service
apiVersion: v1
metadata:
  name:  gateway-svc
spec:
  type: NodePort
  selector:
    app:  gateway-service-app
  ports:
    - port:  8082
      targetPort:  8082